update docker-compose workflow

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -39,5 +39,14 @@ jobs:
 
             cd docker-compose
             docker compose build
-            docker compose up -d --remove-orphans
+           if ! docker compose up -d --remove-orphans; then
+              echo
+              echo "🛑 docker compose up failed – dumping Elasticsearch logs:"
+              echo "========================================================="
+              docker compose logs fileshareappv1-elasticsearch
+              echo "========================================================="
+              exit 1
+            fi
+
+            docker compose logs --tail=50 fileshareappv1-elasticsearch
           EOF
